### PR TITLE
Mongoid Support

### PR DESCRIPTION
**Pull request by mikwat**
Adapt to work with either ActiveRecord or Mongoid. This takes a slightly different approach for Mongoid, since no migration is necessary. Instead, it creates a user session model with the required fields.

Also added some basic tests.

@madkins

### CODE REVIEW

**Comment by mikwat** [comment]
Any thoughts @madkins ?

**Comment by madkins** [comment]
Thanks for the PR - I actually just saw the notification for it today (I have the emails turned off), but will try to take a look through this weekend. The main piece I'll need to spend time with is the test coverage. Is this implementation based on a known best practice, or did you need to make your own strategy?
When I wrote this I just tested in context of the application using it, so unfortunately didn't spend much time thinking about testing in isolation.

**Comment by mikwat** [comment]
Hey @madkins This test dummy app is standard. It's created when you run `rails plugin new <plugin>`. See more here: http://guides.rubyonrails.org/plugins.html

**Comment by madkins** [comment]
Squashed/merged by https://github.com/madkins/devise_invalidatable/issues/2

**Comment by mikwat** [comment]
:+1:

**Pull request closed without merging**
